### ISSUE TITLE
Remove xblockutils package

### ISSUE THREAD

**Issue by farhan** [openedx/xblock-image-explorer#107]
Parent ticket: https://github.com/openedx/axim-engineering/issues/915

This repository is using the [xblock-utils](https://github.com/openedx/xblock-utils/) package which has been deprecated and migrated to within the xblock package.

In this ticket, we will:
```[tasklist]
### Tasks
- [ ] Make sure the repository is using xblock [version 1.8.1](https://github.com/openedx/XBlock/releases/tag/xblock-1.8.0) or above. Upgrade the version if required, preferably via the `make upgrade` command.
- [ ] Remove the `xblock-utils` package
- [ ] Find and replace all the `xblockutils.*` imports with `xblock.utils.*`
- [ ] Make sure all the test cases are passing
- [ ] Test the xblock
- [ ] remove bok-choy pacakge as well
```

**Comment by feanil** [comment]
This was done as a part of https://github.com/openedx/xblock-image-explorer/pull/108 along with the bokchoy removal.
